from pathlib import Path
import ast,json
ROOT=Path(__file__).resolve().parents[1]
# Reuse only imports and helper definitions; never execute the v2.1 authoring block.
helper=ast.parse((ROOT/'scripts/make_equalization_document.py').read_text())
selected=[n for n in helper.body if isinstance(n,(ast.Import,ast.ImportFrom,ast.FunctionDef))]
exec(compile(ast.Module(body=selected,type_ignores=[]),'document_helpers','exec'))
f=json.loads((ROOT/'site/data/portfolio-microsoft-finance.json').read_text())
i=json.loads((ROOT/'site/data/portfolio-microsoft-impact.json').read_text())
metrics={m['id']:m for m in f['metrics']}
fmt=lambda n:f'{n:,.2f}'.rstrip('0').rstrip('.').replace(',','X').replace('.',',').replace('X','.') if isinstance(n,(int,float)) else 'Não determinado'
# All source values are integers except hypothesis outputs, so use exact locale formatting.
def nv(n):
 if n is None:return 'Não determinado'
 if float(n).is_integer():return f'{int(n):,}'.replace(',','.')
 return f'{n:,.2f}'.replace(',','X').replace('.',',').replace('X','.')
def source(label,url):
 pa=doc.add_paragraph();hyperlink(pa,label,url)
def page(title):doc.add_page_break();h(doc,title)
def row(id,label=None):return [label or metrics[id]['label']]+[nv(metrics[id]['values'][y]) for y in f['periods']]
doc=new('Portfólio empresarial Microsoft','Conciliação documental e revisão de impacto FY2025')
for s in doc.sections:
 s.page_width=Cm(21.59);s.page_height=Cm(27.94)
 for pa in s.footer.paragraphs:
  for r in pa.runs:r.text=r.text.replace('v2.1','v2.2')
p(doc,'ÍNDOLE 360 • Idealização de Aldenir Rocha • Versão 2.2 • 18 setembro 2026')
p(doc,'As demonstrações públicas da Microsoft foram conciliadas aritmeticamente para três exercícios. As 12 conferências de fluxo e caixa fecham sem diferença. A revisão de impacto identificou informações ambientais com asseguração limitada, ações educacionais corroboradas por parceiro e lacunas que impedem calcular a contribuição própria líquida e a adesão ao modelo 30/30/30/10.')
p(doc,'O objetivo é orientar consumo responsável e diálogo com empresas. Este dossiê não atribui nota moral e não substitui auditoria contábil, asseguração de impacto ou avaliação profissional independente.')
h(doc,'Escopo e leitura',2)
p(doc,'Entidade: Microsoft Corporation e controladas, NASDAQ MSFT, Estados Unidos. Base financeira: princípios contábeis dos Estados Unidos (US GAAP), consolidada, em USD milhões. FY2025 vai de 1º de julho de 2024 a 30 de junho de 2025. FY significa exercício fiscal. A série cobre FY2023, FY2024 e FY2025; o documento-base uniforme é o Annual Report 2025.')
p(doc,'A ficha FY2026 do catálogo foi preservada. O recorte FY2025 permite confrontar as contas com indicadores ambientais publicados em 2026; cada indicador mantém seu período e perímetro. Aquisições e revisões metodológicas limitam inferências sobre crescimento orgânico.')
h(doc,'Dimensão econômica',2)
table(doc,['USD milhões salvo empregados','FY2023','FY2024','FY2025'],[row('revenue','Receita'),row('net_income','Lucro líquido'),row('research_development','Pesquisa e desenvolvimento'),row('cash_capex','Adições ao imobilizado em caixa'),row('cash_dividends_paid','Dividendos pagos'),row('cash_buybacks','Recompras pagas'),row('employees','Empregados aproximados')],[8.0,3.0,3.0,3.0])
p(doc,'Roteiro: 1. Escopo e dimensão econômica • 2. Conciliação do caixa • 3. Impacto ambiental • 4. Pessoas e programas • 5. Proposta e comprovantes • 6. Fontes e continuidade')
source('Fonte financeira e parecer Deloitte de 30 julho 2025',f['sources'][0]['url'])
page('Conciliação do caixa e dos investimentos')
p(doc,'Os valores abaixo mantêm o sinal da demonstração. O cálculo parte do caixa inicial, soma operações, investimentos, financiamento e efeito cambial e chega ao saldo final. Nenhuma rubrica ausente foi convertida em zero.')
table(doc,['Ponte do caixa em USD milhões','FY2023','FY2024','FY2025'],[row(k,l) for k,l in [('cash_begin','Caixa inicial'),('cfo','Fluxo operacional'),('cfi','Fluxo de investimentos'),('cff','Fluxo de financiamento'),('fx_effect','Efeito cambial'),('cash_end','Caixa final')]]+[['Resíduo calculado menos publicado','0','0','0']],[8,3,3,3])
p(doc,'As somas internas dos fluxos operacional, de investimentos e de financiamento também reproduzem os totais em cada ano. São 12 verificações: quatro por exercício. A planilha e o JSON preservam todas as parcelas e permitem repetir os cálculos.')
h(doc,'Aplicações financeiras em FY2025',2)
p(doc,'Compras de investimentos somaram US$ 29.775 milhões; vencimentos, US$ 16.079 milhões; vendas, US$ 9.309 milhões. O movimento dessas três linhas é saída líquida de US$ 4.387 milhões. O total de investimentos de caixa é saída de US$ 72.599 milhões e inclui imobilizado, aquisições, intangíveis e outros movimentos.')
p(doc,'A compra bruta não prova aplicação integral do lucro do ano nem sua motivação. A carteira também cumpre funções de liquidez. Para aplicar os critérios autorais de honra, faltam o vínculo entre cada recurso, suas obrigações e o destino final.')
h(doc,'Versões e dupla contagem',2)
p(doc,'A publicação FY2026 reapresenta dois componentes comparativos de FY2025: depreciação, amortização e outros passa de 34.153 a 29.433, e perdas de investimentos e derivativos de 609 a 5.329. A compensação é 4.720; o fluxo operacional continua 136.162. Esta entrega usa exclusivamente a apresentação AR2025 nas pontes.')
p(doc,'Recompras em caixa de 18.420 diferem dos 13.000 sob o programa autorizado. A nota 15 informa ações retidas para tributos de empregados em valores arredondados; a diferença exata não deve ser atribuída integralmente sem conciliar liquidação e arredondamento. Arrendamentos financeiros sem caixa de 20.511 não entram no capex de caixa.')
h(doc,'Parecer financeiro original',2)
p(doc,'Deloitte & Touche LLP, 30/07/2025: opinião sem ressalva sobre as demonstrações abrangidas. Reconhecimento de receita e posições fiscais incertas foram matérias críticas de auditoria. O parecer não certifica este catálogo, o modelo de destinação ou seus resultados socioambientais.')
page('Impacto ambiental e alcance da asseguração')
p(doc,'O parecer Deloitte de 09/07/2026 é uma revisão limitada da informação especificada na seção 1 do Environmental Data Fact Sheet 2026, referente ao FY2025, e do indicador de plástico de uso único em 31/12/2025. Exclui seção 2, períodos anteriores, projeções, metas, progresso contra metas e outras narrativas. O escopo não abrange programas sociais.')
table(doc,['Indicador da mesma edição','FY2024','FY2025','Variação'],[[c['metric']+' ('+c['unit']+')',nv(c['FY24']),nv(c['FY25']),nv(c['change_pct'])+'%'] for c in i['comparisons']],[8,3,3,3])
p(doc,'GHG é a sigla inglesa para gases de efeito estufa; tCO₂e significa toneladas de dióxido de carbono equivalente. As tabelas 1A e 1B usam critérios distintos e não se somam. Na tabela 1A, o total usa Escopo 2 pelo método market-based. Não se adiciona o total location-based ao mesmo inventário.')
p(doc,'FY2024 foi reexpresso nesta edição e está fora da revisão limitada de 2026. Mudanças nos fatores, na captura de dados e no uso de certificados de energia influenciam a comparação. As variações descritivas não demonstram que toda a mudança seja física nem atribuem causalidade.')
h(doc,'Água e compromissos futuros',2)
p(doc,'ML significa milhão de litros: 1 ML equivale a 1.000 m³. A retirada de 13.266 ML corresponde a 13,266 milhões de m³. Cerca de 50% da retirada ocorreu em regiões de estresse hídrico. A reposição global reportada superior a 14,2 milhões de m³ não demonstra equilíbrio em cada bacia ou para cada comunidade.')
p(doc,'O relatório informa 45 milhões de toneladas de remoção de carbono contratadas em FY2025 para entregas futuras. Contratos não neutralizam automaticamente as emissões do exercício. O reúso ou reciclagem de 92% dos servidores e componentes desativados se refere ao fluxo descrito; não representa a circularidade de todos os produtos.')
source('Environmental Data Fact Sheet 2026 páginas 3 a 7 e parecer na página 23',i['assurance']['url'])
source('Environmental Sustainability Report 2026',i['sources'][1]['url'])
page('Pessoas doações e execução de programas')
h(doc,'Trabalhadores',2)
p(doc,'O relatório anual informa aproximadamente 228 mil empregados de tempo integral em 30/06/2025. O número é uma posição de encerramento e não revela empregos líquidos criados, satisfação, promoção ou qualidade das condições. A nota 17 informa US$ 1,8 bilhão em benefícios previdenciários patronais no FY2025, reconhecidos como despesa. O valor já afeta o lucro e não deve ser contado novamente como destinação adicional.')
p(doc,'A oferta de aprendizagem contínua é descrita, mas o custo e as horas internas de FY2025 não foram identificados nesta coleta. Permanecem necessários indicadores de progressão, retenção, participação, remuneração e satisfação, com metodologia e proteção de dados pessoais.')
h(doc,'Doações e anúncios com perímetros diferentes',2)
p(doc,'O Annual Report e o Impact Summary 2025 apresentam US$ 263 milhões de doações de empregados com contrapartida empresarial. A página de employee engagement apresenta US$ 255,6 milhões em 2025. O recorte temporal e o perímetro não foram conciliados: não somar os valores nem atribuir o total à empresa. O valor isolado da contrapartida e o benefício fiscal efetivo continuam desconhecidos.')
p(doc,'Elevate anunciou mais de US$ 4 bilhões em dinheiro e tecnologia de IA e nuvem para cinco anos, em 09/07/2025, após o encerramento do FY2025. O compromisso e a meta de credenciais não equivalem a desembolso FY2025 ou empregos gerados. Tecnologia doada, desconto, preço de lista e custo corporativo exigem campos distintos.')
h(doc,'Programa com execução corroborada',2)
p(doc,'O Gateway Technical College, no relatório acadêmico 2024–2025, página 9, confirma formação de educadores em 2024, certificado IT–Microsoft Data Center de dois semestres e quatro disciplinas, e apoio financeiro da Microsoft a estudantes. O parceiro fornece evidência de execução, sem quantificar neste registro o valor, os concluintes ou empregos atribuíveis. A instituição executora não é auditor independente.')
h(doc,'Conclusão de impacto',2)
p(doc,'Há ações e indicadores documentados. Ainda não há total FY2025 conciliado de contribuição corporativa em caixa, tecnologia e contrapartida. Benefícios fiscais, repasses de terceiros e devoluções não podem ser preenchidos por estimativa. O total próprio líquido permanece não determinado.')
for url,label in [(i['sources'][3]['url'],'Impact Summary 2025'),('https://blogs.microsoft.com/on-the-issues/2025/07/09/elevate/','Anúncio Elevate'),('https://www.microsoft.com/en-us/corporate-responsibility/philanthropies/employee-engagement','Employee engagement'),('https://www.gtc.edu/documents/gateway-annual-report-2024-2025','Relatório Gateway 2024–2025')]:source(label,url)
page('Proposta de destinação e solicitação documental')
p(doc,'A regra autoral 30/30/30/10 é uma hipótese normativa. O lucro líquido FY2025 de US$ 101.832 milhões produziria as referências abaixo. A tabela não constitui obrigação legal, dívida, valor já executado nem projeção de impacto.')
table(doc,['Destino proposto','Proporção','USD milhões'],[['Produto','30%','30.549,6'],['Pessoas','30%','30.549,6'],['Social ambiente e humanitário','30%','30.549,6'],['Reserva','10%','10.183,2']],[10,3,4])
p(doc,'Na base alternativa de três anos, o lucro soma US$ 262.329 milhões: cada parcela de 30% seria 78.698,7 e a de 10%, 26.232,9. Essa alternativa substitui a base anual. Somar as janelas duplicaria lucros. Nenhum aporte elegível foi creditado; aderência e saldo a contribuir permanecem desconhecidos, não zero.')
h(doc,'Minuta de solicitação à Microsoft',2)
p(doc,'À equipe de Relações com Investidores, Sustentabilidade e Pessoas da Microsoft,')
p(doc,'O projeto ÍNDOLE 360 reúne informações públicas para compreender a relação entre resultados econômicos, trabalho e impacto. Reconhecemos as ações documentadas e desejamos corrigir eventuais lacunas com a colaboração da empresa. Solicitamos, quando publicável, informações relativas ao exercício encerrado em 30/06/2025:')
for t in ['Relação de aportes por projeto e beneficiário final, entidade pagadora, data, moeda, valor executado, comprovante e identificador único.','Separação entre caixa corporativo, doações de empregados, contrapartidas, recursos de terceiros, produtos e descontos; critério de mensuração, benefício fiscal efetivo e devoluções.','Conciliação com as contas financeiras, tratamento como despesa ou outra rubrica, compromissos ainda não executados e prevenção de duplicidades entre projetos e empresas do grupo.','Indicadores de trabalhadores e resultados dos programas, com linha de base, métodos, cobertura, limitações, efeitos adversos e escopo de verificação independente.'] :p(doc,t,'List Bullet')
p(doc,'Propomos divulgação de uma tabela anual padronizada e diálogo com trabalhadores e beneficiários. A ausência de um dado será registrada como não determinado. Agradecemos esclarecimentos e ofereceremos espaço para correção e resposta, sem atribuir intenção ou conduta além da evidência.')
p(doc,'Minuta preparada para revisão. Não enviada nesta atualização; correspondências anteriores não foram repetidas.')
page('Fontes arquivos e continuidade')
p(doc,'Consulta em 18/09/2026. Cada registro do JSON preserva a fonte e o localizador. O material foi examinado por frentes de contabilidade e impacto, com integração e checagem aritmética. Isso não constitui revisão externa independente. A revisão separada do GPT permanece ausente.')
for s in f['sources'][:5]:source(s['title'],s['url'])
for s in i['sources']:
 if 'ar25' not in s['url']:source(s['title'],s['url'])
h(doc,'Arquivos para reproduzir',2)
p(doc,'Microsoft_Portfolio_FY2025.xlsx contém as fórmulas e fontes. portfolio-microsoft-finance.json contém a série e todas as parcelas; portfolio-microsoft-impact.json contém os 44 registros de impacto. O código do site inclui verificações para dados ausentes, diferença de sinal, duplicação de janelas e preservação de valores desconhecidos.')
source('Dossiê público Microsoft','https://aldenirfilho.github.io/INDOLE-360/portfolio-microsoft.html')
source('Repositório e histórico','https://github.com/aldenirfilho/INDOLE-360')
h(doc,'Projetos agendados',2)
p(doc,'19/09/2026 às 10h de Sobral: Índole dos Impostos, preservando o lembrete anterior. Em 21/09/2026 às 10h, um único lembrete reúne Índole da Saúde, Índole da Mídia, Índole da Educação, Índole Política e Inversão dos Impostos e do Formato de Cobrança. Agenda no fuso America/Fortaleza.')
p(doc,'A inversão dos impostos será estudada como hipótese de desenho de política pública. O primeiro recorte é mapear base, contribuinte, momento e meio de cobrança, comparando efeitos distributivos, arrecadação e manutenção dos serviços essenciais. Os lembretes não iniciam automaticamente publicação, pesquisa contínua ou correspondência.')
h(doc,'Próxima evidência necessária',2)
p(doc,'Conseguir o livro de aportes e uma resposta documental da empresa; depois submeter os dados a contador e avaliador de impacto. Só então recalcular contribuições elegíveis e examinar se há base suficiente para uma avaliação comparável de índole.')
for border in doc.element.xpath('.//w:pBdr'):border.getparent().remove(border)
out=ROOT/'site/documentos/05_Portfolio_Microsoft_FY2025.docx';doc.save(out);print(out)
